version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app-api:
    depends_on:
      - mysqldb
    build: ./app-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=$MYSQL_USERNAME
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_PORT=$MYSQL_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN 
    networks:
      - backend
      - frontend 

  app-ui:
    depends_on:
      - app-api 
    build: 
      context: ./app-ui 
      args:
        - REACT_APP_API_BASE_URL=$REACT_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT 
    networks:
      - frontend
      
volumes:
  db: 

networks:
  backend:
  frontend: