export type LocationTypes = {
    id?: number | undefined;
    google_formatted_address: string;
    latitude: number;
    longitude: number;
    occupancyname: string;
    mutual_aids: string[];
    occupancyaddress: string;
    occupancycity: string;
    occupancystate: string;
    occupancyzip: string;
    occupancycountry: string;
    construction_types: string[];
    hazards: string;
    hydrant_address: string;
    hydrant_distance: number;
    access: string;
    electric_meter: string;
    breaker_box: string;
    water: string;
    gas_shutoff: string;
    emergency_contact_number: string;
    other_notes: string;
    occupancy_types: string[];
    contactname: string;
};